### ISSUE TITLE
Errors and warnings when building

### ISSUE THREAD

**Issue by code-hunger** [doreminiature/miniature#3]
Here's the output of `npm install` run the first time:

```
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue   
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.                                        
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue                         
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue                           
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN miniature@0.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2:
wanted {"os":"darwin","arch":"any"} (current: {
"os":"linux","arch":"x64"})                                                                                       
```
Next, `grunt build`:
```
>> Local Npm module "grunt-electron-installer-debian" not found. Is it installed?
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.         
```
I'm running Arch Linux so I suppose Debian packages are of no use for me. And the missing task `build` of course makes it somehow mysterious the way to build it.

**Comment by LucaT1** [comment]
I belive you should run `grunt linuxBuild`

[Source](https://github.com/doreminiature/miniature/blob/master/Gruntfile.js#L219)

**Comment by code-hunger** [comment]
Yes, I just grepped the Gruntfile and saw it was called `linuxBuild`, though the README clearly states that the build command is `grunt build`.
Here's the output of `grunt linuxBuild`:
```
Running "concat:browser" (concat) task
File dist/build.js created.

Running "uglify:browser" (uglify) task
JS_Parse_Error {
  message: 'Name expected',
  filename: 'build.js',
  line: 291,
  col: 7,
  pos: 8109,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/home/user/miniature/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1508:18)\n    at js_error (eval at <anonymous> (/home/user/miniature/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1516:11)\n    at croak (eval at <anonymous> (/home/user/miniature/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2008:9)\n    at as_symbol (eval at <anonymous> (/home/user/miniature/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2639:27)\n    at vardefs (eval at <anonymous> (/home/user/miniature/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2414:25)\n    at const_ (eval at <anonymous> (/home/user/miniature/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2436:27)\n    at eval (eval at <anonymous> (/home/user/miniature/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2179:30)\n    at eval (eval at <anonymous> (/home/user/miniature/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2055:24)\n    at eval (eval at <anonymous> (/home/user/miniature/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2802:23)\n    at Object.parse (eval at <anonymous> (/home/user/miniature/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2812:7)\n    at /home/user/miniature/node_modules/grunt-contrib-uglify/tasks/lib/uglify.js:52:27\n    at Array.forEach (<anonymous>)\n    at Object.exports.minify (/home/user/miniature/node_modules/grunt-contrib-uglify/tasks/lib/uglify.js:36:11)\n    at /home/user/miniature/node_modules/grunt-contrib-uglify/tasks/uglify.js:139:25\n    at Array.forEach (<anonymous>)\n    at Object.<anonymous> (/home/user/miniature/node_modules/grunt-contrib-uglify/tasks/uglify.js:61:16)' }
>> Uglifying source dist/build.js failed.
Warning: Uglification failed.
Name expected.
Line 291 in dist/build.js
 Use --force to continue.

Aborted due to warnings.                                                                                  
```
I also installed the debian package, anyway. I'll try with `--force`, now.

**Comment by LucaT1** [comment]
I think(never used grunt before) that force just keeps going on even when there are errors, so you won't have much luck with that.

**Comment by doreminiature** [comment]
Try without uglification.
grunt.registerTask('linuxBuild', ['concat:browser', 'concat:webview', , 'concat:main', 'electron:linuxBuild', 'electron-installer-debian:linux32', 'electron-installer-debian:linux64'])

As for readme, yep my bad,.

**Comment by code-hunger** [comment]
Yes. It continued to the next task. But what was surprising to me was that it downloaded electron for some reason, although I have it installed globally. Then it gave me this error:
```
npm ERR! May not delete: /tmp/electron-packager/linux-ia32/min-linux-ia32/resources/app/node_modules/.bin
```
Trying without uglification now...

**Comment by LucaT1** [comment]
Electron is needed to be in the local node_modules so that's normal.

For the last error try running the command with sudo

**Comment by code-hunger** [comment]
The problem is not with the rights (/tmp is 777), actually the file is missing.

**Comment by code-hunger** [comment]
Actually I just ran `electron .` and it started! Turns out no building is required.

**Comment by LucaT1** [comment]
I belive so. But anyway we're going to rewrite the browser and we're going to give it a material design feel but keeping all the advantages from other browsers. We'd like contributors or even testers! :tada:

**Comment by code-hunger** [comment]
There is a typo in the repo url in the home page. Here's a patch:
```
diff --git a/js/sessionRestore.js b/js/sessionRestore.js                                                                             
index 25b27e1..e80535e 100644
--- a/js/sessionRestore.js
+++ b/js/sessionRestore.js
@@ -23,7 +23,7 @@ var sessionRestore = {
       tasks.setSelected(tasks.add()) // create a new task
 
       var newTab = currentTask.tabs.add({
-        url: 'https://github.com/doremininiature/miniature'
+        url: 'https://github.com/doreminiature/miniature'
       })
       addTab(newTab, {
         enterEditMode: true
```

**Comment by code-hunger** [comment]
> we're going to rewrite the browser and we're going to give it a material design feel but keeping all the advantages from other browsers. We'd like contributors or even testers! :tada:
@LucaT1 If you're going to rewrite the browser - do you have any plans on how to do this? Any open forum/discussion on how you'll start it and how it will progress?

**Comment by LucaT1** [comment]
We do. Just come to talk on discord/gitter with me and doreminiature! https://discord.gg/yAA8DdK

**Comment by doreminiature** [comment]
As Luca said, eventually we will make it from scratch. 
For now we stick to work with Min codebase. 
We plan to properly implement Miniature features during next 3 weeks and release an early alpha. @code-hunger @StekolschikovV
